name: Main

on:
  push:
    branches:
    - main

jobs:
  build-packer-images:
    uses: packer.yml
    strategy:
      matrix:
        image_directory:
        - windows/ue5-agent
    with:
      image_version: latest
    secrets:
      packer_azure_credentials: ${{ secrets.PACKER_AZURE_CREDENTIALS }}
      packer_client_id: ${{ secrets.PACKER_CLIENT_ID }}
      packer_client_secret: ${{ secrets.PACKER_CLIENT_SECRET }}
      packer_subscription_id: ${{ secrets.PACKER_SUBSCRIPTION_ID }}
      packer_tenant_id: ${{ secrets.PACKER_TENANT_ID }}
      packer_artifacts_resource_group: ${{ secrets.PACKER_ARTIFACTS_RESOURCE_GROUP }}
      packer_build_resource_group: ${{ secrets.PACKER_BUILD_RESOURCE_GROUP }}
