name: Packer

on:
  workflow_call:
    inputs:
      image_directory:
        required: true
        type: string
      image_version:
        required: true
        type: string
    secrets:
      packer_azure_credentials:
        required: true
      packer_client_id:
        required: true
      packer_client_secret:
        required: true
      packer_subscription_id:
        required: true
      packer_tenant_id:
        required: true
      packer_artifacts_resource_group:
        required: true
      packer_build_resource_group:
        required: true

jobs:
  check_manifest:
    name: Fetch image from manifest
    runs-on: ubuntu-latest
    outputs:
      publisher: ${{ steps.fetch_publisher.outputs.value }}
      offer: ${{ steps.fetch_offer.outputs.value }}
      sku: ${{ steps.fetch_sku.outputs.value }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Fetch Publisher
      id: fetch_publisher
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'jq .publisher ${{ inputs.image_directory }}/manifest.json -r'

    - name: Fetch Offer
      id: fetch_offer
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'jq .offer ${{ inputs.image_directory }}/manifest.json -r'

    - name: Fetch SKU
      id: fetch_sku
      uses: sergeysova/jq-action@v2
      with:
        cmd: 'jq .sku ${{ inputs.image_directory }}/manifest.json -r'

  build:
    name: Run Packer
    runs-on: ubuntu-latest
    needs: [check_manifest]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Validate Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ./${{ inputs.image_directory }}/template.pkr.hcl

    - name: Build Packer Image
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -color=false
        target: ./${{ inputs.image_directory }}/template.pkr.hcl
      env:
        PKR_VAR_client_id: ${{ secrets.packer_client_id }}
        PKR_VAR_client_secret: ${{ secrets.packer_client_secret }}
        PKR_VAR_subscription_id: ${{ secrets.packer_subscription_id }}
        PKR_VAR_tenant_id: ${{ secrets.packer_tenant_id }}
        PKR_VAR_artifacts_resource_group: ${{ secrets.packer_artifacts_resource_group }}
        PKR_VAR_build_resource_group: ${{ secrets.packer_build_resource_group }}
        PKR_VAR_source_image_publisher: ${{ needs.check_manifest.outputs.publisher }}
        PKR_VAR_source_image_offer: ${{ needs.check_manifest.outputs.offer }}
        PKR_VAR_source_image_sku: ${{ needs.check_manifest.outputs.sku }}
        PKR_VAR_source_image_version: ${{ inputs.image_version }}

